### ISSUE TITLE
error updating clover

### ISSUE THREAD

**Issue by Dawn13** [JrCs/CloverGrowerPro#19]
terminal stops with following message...
.
.
gcc -Wno-deprecated-declarations -o ../bin/GnuGenBootSector  GnuGenBootSector.o -L../libs -lCommon
ld: file not found: /usr/lib/system/libsystem_stats.dylib for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/GnuGenBootSector] Error 1
make[1]: *** [GnuGenBootSector] Error 2
make: *** [Source/C] Error 2
Cloverx64 release  ERROR!!

what do i need to do to get around this error  ?
any help appreciated

**Comment by Dawn13** [comment]
solved

**Comment by j-bennet** [comment]
@Dawn13 solved how?
