### ISSUE TITLE
Unable to build maybe due to edk

### ISSUE THREAD

**Issue by iPotable** [JrCs/CloverGrowerPro#21]
I was unable to build Clover since OS X 10.11.3 due to Apple gcc upgrade to 5.x. I fixed that issue by building on an earlier version of OS X. Now I'm not able to build any clover version anywhere. I'm not sure but it seems that the last edk version is responsible.

**Comment by chris1111** [comment]
Same issue here 
no build on any version of OS X with GGP

**Comment by cnrd** [comment]
Seems like it's a problem with EDK: https://sourceforge.net/p/cloverefiboot/tickets/231/

**Comment by iPotable** [comment]
the problem seems to be solved.
